drbd_nodes:
  - { name: red41, addr: 172.16.67.241, storage: zfs, leader: True}
  - { name: red42, addr: 172.16.67.242, storage: zfs}
  - { name: red43, addr: 172.16.67.243, storage: zfs}
  - { name: red44, addr: 172.16.67.244, storage: none, client: True}
drbdpool_dev_root: /dev/sdb
drbdpool_dev_path: "{{ drbdpool_dev_root }}1"
corosync_cluster_name: cluster00
corosync_servers: [ red41, red42 ]
corosync_rings:
  - id: 0
    nodes:
      - nodeid: 1
        addr: 172.16.67.241
        name: red41
      - nodeid: 2
        addr: 172.16.67.242
        name: red42

# vim: set ts=2 sw=2 et:
