- name: apt install corosync/pacemaker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
    cache_valid_time: "{{ apt_cache_validate_time }}"
  with_items:
    - pacemaker
    - fence-agents
  tags: [aptinstall, corosync]

- name: set corosync.conf
  template:
    src: corosync.conf.j2
    dest: /etc/corosync/corosync.conf
    backup: yes
  notify: restart corosync
  tags: [corosync]
