# storage-plugin = drbdmanage.storage.zvol.Zvol

- name: check disk partition
  shell: "sgdisk -i1 {{ drbdpool_dev_root }}"
  register: ls_disk_part
  changed_when: False

- name: create disk partition1
  shell: "sgdisk -n 1:0:128M -t 1:8e00 {{ drbdpool_dev_root }}"
  when: ls_disk_part.rc == 0 and ls_disk_part.stdout.find('does not exist') != -1

- name: create disk partition2
  shell: "sgdisk -n 2:0:0 -t 2:bf01 {{ drbdpool_dev_root }}"
  when: ls_disk_part.rc == 0 and ls_disk_part.stdout.find('does not exist') != -1

- name: set drbdpool zpool name
  set_fact: drbdpool_zpool="drbdpool" 

- name: check zpool drbdpool
  shell: "zfs list -t all|grep {{ drbdpool_zpool }}|cat"
  register: check_zpool_drbdpool
  changed_when: False

- name: create drbdpool as zpool
  shell: "zpool create -f {{ drbdpool_zpool }} {{ drbdpool_dev_root }}2 && zfs set mountpoint=none {{ drbdpool_zpool }}"
  when: check_zpool_drbdpool.stdout|length == 0

- name: LVM VG Create
  lvg: vg=drbdpool pvs="{{ drbdpool_dev_root }}1"

# vim: set ts=2 sw=2 et:
