- name: update resolvconf
  shell: /sbin/resolvconf -u
- name: update locales
  shell: /usr/sbin/dpkg-reconfigure -f noninteractive locales
- name: restart autofs
  service: name=autofs state=restarted
- name: restart ntp
  service: name=ntp state=restarted
- name: update systemd_resolved
  systemd:
    name: systemd-resolved.service
    state: restarted
    daemon_reload: yes
