- name: Get Firewall rule to allow mDNS
  win_shell: Get-NetFirewallPortFilter -Protocol TCP | where Localport -eq 5353
  register: firewall_mdns_allow
  changed_when: False
  tags: firewall

- name: Firewall rule to allow mDNS
  win_shell: >
    New-NetFirewallRule -Protocol TCP -LocalPort 5353 -Direction Inbound -Action Allow -DisplayName mDNS-in
  when: firewall_mdns_allow.stdout.strip() == ""
  tags: firewall

- name: Get Firewall rule to allow ping
  win_shell: Get-NetFirewallRule -Direction Inbound| where DisplayName -Like "ファイル*ICMPv4*"| % { $_.Enabled }
  register: firewall_ping_allow
  changed_when: False
  ignore_errors: yes
  tags: firewall

- name: Firewall rule to allow ping
  win_shell: Get-NetFirewallRule -Direction Inbound| where DisplayName -Like "ファイル*ICMPv4*" | \
    Set-NetFirewallRule -Enabled True -Action Allow
  when: "{{ 'False' in firewall_ping_allow.stdout_lines }}"
  tags: firewall

- name: Get Firewall rule to allow RDP
  win_shell: Get-NetFirewallRule| where Name -Like "RemoteDesktop-UserMode-In-TCP*" | % { $_.Enabled }
  register: firewall_rdp_allow
  changed_when: False
  ignore_errors: yes
  tags: firewall

- name: Firewall rule to allow RDP
  win_shell: Get-NetFirewallRule| where Name -Like "RemoteDesktop-UserMode-In-TCP*" | \
    Set-NetFirewallRule -Enabled True -Action Allow
  when: "{{ 'False' in firewall_rdp_allow.stdout_lines }}"
  tags: firewall

- name: settings
  win_regedit:
    key: '{{ item.key }}'
    value: '{{ item.value }}'
    data: '{{ item.data }}'
    datatype: '{{ item.datatype | default("dword") }}'
  with_items:
    - key: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server
      value: fDenyTSConnections
      data: 0
    - key: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
      value: UserAuthentication
      data: 1
    - key: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\DateTime\Servers
      value: 1
      data: "{{ ntp_servers[0] }}"
      datatype: string
    - key: HKLM:\SYSTEM\CurrentControlSet\Services\W32Time\Parameters
      value: NTPServer
      data: "{{ ntp_servers[0] }},0x9"
      datatype: string
  tags: win_settings
