- include: aptproxy.yml

- name: Get hostname
  shell: hostname
  register: hostname
  changed_when: False
  tags: [common, hostname]

- name: Search hostname in hosts
  shell: hostname -i
  register: search_hosts_result
  ignore_errors: yes
  changed_when: False
  tags: [common, hostname]

- name: Set hostname in hosts
  lineinfile:
    dest: /etc/hosts
    insertafter: '^127.0.0.1'
    line: '127.0.1.1 {{ hostname.stdout }}'
    state: present
    create: yes
  when: search_hosts_result|failed
  tags: [common, hostname]

- name: Search resolv.conf dns search
  shell: grep {{ dns_domain }} /etc/resolv.conf
  register: search_domain_result
  ignore_errors: yes
  changed_when: False
  tags: [common, resolvconf]

- name: Set resolv.onf dns search
  lineinfile:
    dest: /etc/resolvconf/resolv.conf.d/base
    regexp: '^search'
    line: 'search {{ dns_domain }}'
    create: yes
  changed_when: True
  when: search_domain_result|failed
  notify: update resolvconf
  tags: [common, resolvconf]

- name: apt install
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
    cache_valid_time: "{{ apt_cache_validate_time }}"
  with_items:
    - vim
    - git
    - curl
    - language-pack-ja
    - bash-completion
    - htop
    - parted
    - gdisk
    - "{{ apt_extra_packages }}"
  async: 180
  poll: 5
  tags: [common, aptinstall]

- name: apt install not lxc
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
    cache_valid_time: "{{ apt_cache_validate_time }}"
  with_items:
    - avahi-daemon
  when: ansible_virtualization_type is defined and ansible_virtualization_type != "lxc"
  tags: [common, aptinstall]

- name: Update all packages to the latest version
  apt:
    upgrade: dist
    autoremove: yes
    update_cache: yes
  async: 180
  poll: 5
  tags: [common, aptinstall]
  when: distupgrade|default("") == "yes"

- name: Set timezone variables
  timezone:
    name: Asia/Tokyo
  tags: [common, timezone]

- name: Set locale
  locale_gen:
    name: ja_JP.UTF-8
    state: present
  notify: update locales
  tags: [common, locale]

- name: Test default locale
  shell: grep -i -e '^LANG="*ja_JP.UTF-8' /etc/default/locale
  register: result
  ignore_errors: yes
  changed_when: False
  tags: [common, locale]

- name: Update default locale
  shell: update-locale LANG="ja_JP.UTF-8"
  when: result|failed
  tags: [common, locale]

- name: create skel .vimrc
  copy: dest='/etc/skel/.vimrc' content='set modeline\n' mode=0644
  tags: [common, skel]

- name: create skel .viminfo
  file: path='/etc/skel/.viminfo' mode=0600 state=touch
  changed_when: False
  tags: [common, skel]

- name: alternatives editor is vim
  file: src=/usr/bin/vim.basic dest=/etc/alternatives/editor state=link
  tags: [common, alternatives]

- name: Set sudoers user/group
  lineinfile:
    dest: "/etc/sudoers.d/{{ item.replace('%', '') }}"
    line: "{{ item }} ALL=(ALL:ALL) ALL"
    create: yes
    mode: 0440
  when: sudoers_users is defined
  with_items: "{{ sudoers_users }}"
  tags: [common, sudoers]

- include: autofs.yml
  when: ansible_virtualization_type is defined and ansible_virtualization_type != "lxc"
  tags: [common, autofs]

- name: create ldap home dir
  file:
    path: "{{ ldap_mkhomedir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: ldap_mkhomedir is defined
  tags: [common, autofs]

- include: ntp.yml
