- name: apt install ntp
  apt:
    name: ntp
    state: latest
    update_cache: yes
    cache_valid_time: "{{ apt_cache_validate_time }}"
  tags: [common, ntp]

- name: Set ntp.conf, remove ubuntu server
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    backup: yes
  when: ntp_servers is defined
  notify: restart ntp
  tags: [common, ntp]
