- name: add apt key zabbix
  apt_key:
    url: "https://repo.zabbix.com/zabbix-official-repo.key"
    state: present
    validate_certs: no
  tags: [common, aptinstall, aptrepo, zabbix]
  environment:
    http_proxy: "{{ http_auth_proxy }}"
    https_proxy: "{{ http_auth_proxy }}"
    no_proxy: "localhost,.{{ dns_domain }}"

- name: add apt repository zabbix
  apt_repository:
    repo: "deb http://repo.zabbix.com/zabbix/3.4/ubuntu {{ ansible_distribution_release }} main"
    filename: 'zabbix'
    state: present
  tags: [common, aptinstall, aptrepo, zabbix]

- name: add apt repository zabbix source
  apt_repository:
    repo: "deb-src http://repo.zabbix.com/zabbix/3.4/ubuntu {{ ansible_distribution_release }} main"
    filename: 'zabbix'
    state: present
  tags: [common, aptinstall, aptrepo, zabbix]

- name: apt install zabbix-agent
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
    cache_valid_time: "{{ apt_cache_validate_time }}"
  with_items:
    - zabbix-agent
  notify: enable zabbix-agent
  tags: [common, aptinstall, zabbix]

- name: setup zabbix_agentd.conf
  template:
    src: zabbix_agentd-linux.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart zabbix-agent
  tags: [common, zabbix]
