- name: install utils packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_validate_time }}"
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: set docker repository url
  set_fact:
    docker_repo_url: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable main'

- name: docker Repository Add.
  apt_repository:
    repo: "{{docker_repo_url}}"
    filename: 'docker'
    state: present

- name: docker Install
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_validate_time }}"
  with_items:
    - docker-ce

- name: check docker-compose
  shell: /usr/local/bin/docker-compose -v
  register: compose_result
  changed_when: False
  ignore_errors: True
  tags: compose

- name: docker-compose install
  shell: 'cmd=$(curl -sSL https://github.com/docker/compose/releases| \
    grep curl| head -n1| sed "s/.*>//") && eval $cmd && \
    chmod +x /usr/local/bin/docker-compose'
  when: compose_result.rc != 0
  tags: compose

# vim: set ts=2 sw=2 et:
