- name: set zabbix repository url
  set_fact:
    zabbix_repo_url: "https://repo.zabbix.com/zabbix-official-repo.key"
  tags: [common, aptinstall, aptrepo, zabbix]

- name: add apt key zabbix
  apt_key:
    url: "{{ zabbix_repo_url }}"
    state: present
    validate_certs: no
  tags: [common, aptinstall, aptrepo, zabbix]
  environment:
    http_proxy: "{{ http_auth_proxy }}"
    https_proxy: "{{ http_auth_proxy }}"
    no_proxy: "localhost,.{{ dns_domain }}"
  when: http_auth_proxy|default('')|length() > 0

- name: add apt key zabbix nouse proxy
  apt_key:
    url: "{{ zabbix_repo_url }}"
    state: present
    validate_certs: no
  tags: [common, aptinstall, aptrepo, zabbix]
  when: http_auth_proxy|default('')|length() == 0

- name: add apt repository zabbix
  apt_repository:
    repo: "deb http://repo.zabbix.com/zabbix/3.4/ubuntu {{ ansible_distribution_release }} main"
    filename: 'zabbix'
    state: present
  tags: [common, aptinstall, aptrepo, zabbix]

- name: apt install zabbix-agent
  apt:
    name: ['zabbix-agent']
    state: latest
    update_cache: yes
    cache_valid_time: "{{ apt_cache_validate_time }}"
  notify: enable zabbix-agent
  tags: [common, aptinstall, zabbix]

- name: setup zabbix_agentd.conf
  template:
    src: zabbix_agentd-linux.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart zabbix-agent
  tags: [common, zabbix]
